"""rename department

Revision ID: 918cd8cbe7d5
Revises: 106a25d86820
Create Date: 2024-10-02 13:31:56.132134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918cd8cbe7d5'
down_revision = '106a25d86820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
